class ProductPostModel {
    int id;
    String name;
    String slug;
    String sku;
    String barcode;
    int stockAmount;
    int price1;
    Brand currency;
    int discount;
    int discountType;
    int moneyOrderDiscount;
    int buyingPrice;
    String marketPriceDetail;
    int taxIncluded;
    int tax;
    int warranty;
    int volumetricWeight;
    String stockTypeLabel;
    int customShippingDisabled;
    int customShippingCost;
    String distributor;
    int hasGift;
    String gift;
    int status;
    int hasOption;
    String shortDetails;
    String searchKeywords;
    String installmentThreshold;
    int homeSortOrder;
    int popularSortOrder;
    int brandSortOrder;
    int featuredSortOrder;
    int campaignedSortOrder;
    int newSortOrder;
    int discountedSortOrder;
    int categoryShowcaseStatus;
    int midblockSortOrder;
    String pageTitle;
    String metaDescription;
    String metaKeywords;
    String canonicalUrl;
    Brand parent;
    Brand brand;
    Brand detail;
    Brand button;
    Brand countDown;
    Brand specialInfo;
    Brand specGroup;
    Brand protection;
    List<dynamic> categories;
    List<dynamic> prices;
    List<dynamic> distributors;
    List<dynamic> extraInfos;
    List<dynamic> images;
    List<dynamic> tags;
    List<dynamic> mappings;
    List<dynamic> selectionGroups;
    List<dynamic> optionGroups;
    List<dynamic> labels;
    List<dynamic> offeredProducts;
    List<dynamic> combineProducts;
    List<dynamic> customizationGroups;
    Brand midblock;
    Brand seoSetting;
    List<dynamic> children;

    ProductPostModel({
        required this.id,
        required this.name,
        required this.slug,
        required this.sku,
        required this.barcode,
        required this.stockAmount,
        required this.price1,
        required this.currency,
        required this.discount,
        required this.discountType,
        required this.moneyOrderDiscount,
        required this.buyingPrice,
        required this.marketPriceDetail,
        required this.taxIncluded,
        required this.tax,
        required this.warranty,
        required this.volumetricWeight,
        required this.stockTypeLabel,
        required this.customShippingDisabled,
        required this.customShippingCost,
        required this.distributor,
        required this.hasGift,
        required this.gift,
        required this.status,
        required this.hasOption,
        required this.shortDetails,
        required this.searchKeywords,
        required this.installmentThreshold,
        required this.homeSortOrder,
        required this.popularSortOrder,
        required this.brandSortOrder,
        required this.featuredSortOrder,
        required this.campaignedSortOrder,
        required this.newSortOrder,
        required this.discountedSortOrder,
        required this.categoryShowcaseStatus,
        required this.midblockSortOrder,
        required this.pageTitle,
        required this.metaDescription,
        required this.metaKeywords,
        required this.canonicalUrl,
        required this.parent,
        required this.brand,
        required this.detail,
        required this.button,
        required this.countDown,
        required this.specialInfo,
        required this.specGroup,
        required this.protection,
        required this.categories,
        required this.prices,
        required this.distributors,
        required this.extraInfos,
        required this.images,
        required this.tags,
        required this.mappings,
        required this.selectionGroups,
        required this.optionGroups,
        required this.labels,
        required this.offeredProducts,
        required this.combineProducts,
        required this.customizationGroups,
        required this.midblock,
        required this.seoSetting,
        required this.children,
    });

}

class Brand {
    List<String> property1;
    List<String> property2;

    Brand({
        required this.property1,
        required this.property2,
    });

}
